### PR TITLE
updated kafka-client dependencies and added 'additionalProperties' property

### PR DESCRIPTION
**Pull request by svendiedrichsen**
Updated kafka-client dependencies to latest release

### CODE REVIEW

**Comment by svendiedrichsen** [comment]
I have just send the signed CLA via email to cla@payara.org. Please consider this PR.

Are you planning a new release of this connector project?

**Comment by smillidge** [comment]
We will release regularly. We haven;t really done the official announcement yet to gain feedback so it will likely be after that.

**Comment by svendiedrichsen** [comment]
Do you have any rough plans on when this may happen. Sorry to insist but we need to plan our release schedule and would like to know if we have to build our own release of this connector. Thanks for your patience.

**Comment by smillidge** [comment]
What's your release date?

**Comment by svendiedrichsen** [comment]
That's subject of the current planning. But deadline would be somewhere around September.

**Comment by smillidge** [comment]
We'll be having a release before then as there are other things under development. For production usage our support also covers Cloud Connectors usage in Payara http://www.payara.fish/support/ :-)

**Comment by svendiedrichsen** [comment]
Is there a SNAPSHOT repository from which we can use the current state of the 0.2.0-SNAPSHOT version of the connectory publicly available?

**Pull request merged**
