### PR TITLE
FISH-6609 Jakartaee10

### PR DESCRIPTION
**Pull request by ehsavoie**
Updating the poms to 0.9.0-SNAPSHOT
Moving to JakartaEE 10

### CODE REVIEW

**Comment by ehsavoie** [comment]
Supersedes https://github.com/payara/Cloud-Connectors/pull/585

**Comment by JamesHillyard** [comment]
Hi @ehsavoie,

Thank you for submitting a contribution for our Cloud Connectors, it's much appreciated. I have raised the internal issue `FISH-6609` for a member of our development team to give this a full technical review.

As this version wouldn't be compatible with Payara 5, we are going to discuss internally a consistent versioning scheme to easily differentiate Payara 5 compatible versions from Payara 6 compatible versions. Due to this, a review may take longer than usual, your patience in the meantime is much appreciated.

Best Regards,
James

**Comment by ehsavoie** [comment]
@JamesHillyard no problem. That's why I also moved the version to 0.9.0-SNASPHOT. JFYI I managed to have WildFly 27 connect to Kafka properly with JakartaEE 10

**Comment by JamesHillyard** [comment]
Hi @ehsavoie,

Thank you for your patience with this, we have been testing these changes on Payara 6 and all seems to work well so thank you for the PR. Before we can proceed with merging this, you will need to sign the CLA and send it to us. [Payara CLA](https://github.com/payara/Payara/blob/master/PayaraCLA.pdf)

After the CLA has been signed and received, we will gladly merge these changes.

Thanks,
James

**Comment by ehsavoie** [comment]
Signed CLA sent

**Comment by JamesHillyard** [comment]
Hi @ehsavoie,

Unfortunately, I was unable to push the resolutions to the merge conflicts and version increments to your branch. I have therefore cherry-picked your changes and incremented the version numbers using the strategy we decided internally into a new PR here: https://github.com/payara/Cloud-Connectors/pull/680.

Your changes are much appreciated, and we are very glad to accept them.

Best Regards,
James

**Pull request closed without merging**
